// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Feed struct {
	Title string
	Url   string
}

type FeedItem struct {
	FeedTitle   string
	Guid        string
	PubDate     int64
	ProcessedAt sql.NullInt64
}
