// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const saveFeed = `-- name: SaveFeed :exec
insert into feed (title, url)
values (?, ?)
`

type SaveFeedParams struct {
	Title string
	Url   string
}

func (q *Queries) SaveFeed(ctx context.Context, arg SaveFeedParams) error {
	_, err := q.db.ExecContext(ctx, saveFeed, arg.Title, arg.Url)
	return err
}

const saveFeedItem = `-- name: SaveFeedItem :exec
insert into feed_item (feed_title, guid, pub_date, processed_at)
values (?, ?, ?, ?)
`

type SaveFeedItemParams struct {
	FeedTitle   string
	Guid        string
	PubDate     int64
	ProcessedAt sql.NullInt64
}

func (q *Queries) SaveFeedItem(ctx context.Context, arg SaveFeedItemParams) error {
	_, err := q.db.ExecContext(ctx, saveFeedItem,
		arg.FeedTitle,
		arg.Guid,
		arg.PubDate,
		arg.ProcessedAt,
	)
	return err
}
